apiVersion: batch/v1
kind: Job
metadata:
  name: delete-job
  namespace: default
  generateName: delete-job
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-1"
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: provision
      imagePullSecrets:
      - name: kotsadm-replicated-registry
      containers:
      - name: preflights-aif
        image: aifabriconprem.azurecr.io/on-prem/daemon-script:v20.10.1
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh","-c"]
        args: ["kubectl get job | grep support-dump | cut -d ' ' -f1 | xargs -l1 --no-run-if-empty -- sh -c 'kubectl delete job $0'"]
      restartPolicy: Never