apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: support-dump
  name: support-dump
  namespace: default
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: provision
      imagePullSecrets:
      - name: kotsadm-replicated-registry
      containers:
      - image: 'aifabriconprem.azurecr.io/on-prem/support-dump:argocd1'
        name: support-dump
        imagePullPolicy: Always
      restartPolicy: Never