ingress:
  host: IP_ADDRESS_OF_KUBERNETES_INSTANCE
orchestrator:
  endpoint: ORCHESTRATOR_IP:ORCHESTRATOR_PORT
identityserver:
  endpoint: IDENTITY_SERVER_IP:IDENTITY_SERVER_PORT
identity:
  accessToken: eyJhbGciOiJSUzI1NiIsImtpZCI6IjUzRjE2Q0UyQjg3RTQ1RUU1RDgwOTRERjc5NjJEN0MzOTYxNjcyN0UiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJVX0ZzNHJoLVJlNWRnSlRmZVdMWHc1WVdjbjQifQ
sql:
  host: DATABASE_IP
  username: admin
  password: password
dbname:
  aiHelper: ai_helper
  aiDeployer: ai_deployer
  aiPkgManager: ai_pkgmanager
  aiTrainer: ai_trainer
  aiAppManager: ai_appmanager
registry:
  Namespace: default
  isAirgap: false